# Generated by Django 3.1.7 on 2021-06-13 14:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycleTimeStart', models.DateTimeField(verbose_name='Start date')),
                ('cycleTimeEnd', models.DateTimeField(verbose_name='End date')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryId', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Category ID')),
                ('categoryName', models.CharField(default='Other', max_length=30, unique=True, verbose_name='Name of the category')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0, 'Transaction amount must be >= 0.')], verbose_name='Amount of money in the transaction')),
                ('time', models.DateTimeField(null=True, verbose_name='Time on the transaction')),
                ('note', models.CharField(blank=True, max_length=150, verbose_name='Note')),
                ('categoryId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='Budget.category', verbose_name='Category')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_backend.user', verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='SavingGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goalAmount', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0, 'Saving goal amount must be > 0')], verbose_name='Amount of money user want to save')),
                ('currentAmount', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0, 'Current amount must be > 0')], verbose_name='Current amount')),
                ('duration', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Saving goal duration must be > 1 day')], verbose_name='Duration of the goal (days)')),
                ('startDate', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Start Date')),
                ('endDate', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='End Date')),
                ('isComplete', models.BooleanField(default=False)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0, 'Budget goal amount must be > 0')], verbose_name='Amount of money')),
                ('source', models.CharField(blank=True, max_length=30, verbose_name='Money source')),
                ('date', models.DateTimeField(null=True, verbose_name='Date')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetGoalCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0, 'Budget goal amount must be > 0')], verbose_name='Amount of money')),
                ('budgetGoalid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Budget.budgetgoal')),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Budget.category')),
            ],
            options={
                'unique_together': {('budgetGoalid', 'categoryId')},
            },
        ),
    ]
