# Generated by Django 3.1.7 on 2021-06-13 14:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('content', models.CharField(max_length=300)),
                ('point', models.IntegerField(default=0)),
                ('post_date', models.DateField(default=datetime.date.today)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fp_comment_related', to='budget_backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(default=0)),
                ('post_date', models.DateField(default=datetime.date.today)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fp_plan_related', to='budget_backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='PlanComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fp.comment')),
                ('parent_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fp.plan')),
            ],
        ),
        migrations.CreateModel(
            name='ParentChildComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fp.comment')),
                ('parent_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fp_parentchildcomment_related', to='Fp.comment')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fp_follow_related', to='budget_backend.user')),
                ('following_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_backend.user')),
            ],
        ),
    ]
