# Generated by Django 3.1.7 on 2021-06-13 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_backend.stock')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('average_price', models.FloatField(null=True)),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_backend.stock')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('order_type', models.CharField(choices=[('SELL', 'SELL'), ('BUY', 'BUY')], default='BUY', max_length=30)),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_backend.stock')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price_bought', models.FloatField(null=True)),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_backend.stock')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_backend.stock')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_backend.user')),
            ],
            options={
                'unique_together': {('stock_id', 'user_id')},
            },
        ),
    ]
