# Generated by Django 3.1.7 on 2021-06-13 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('abbreviation', models.CharField(max_length=8)),
                ('current_price', models.FloatField()),
                ('frequency', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('balance', models.FloatField(default=0.0)),
                ('full_name', models.CharField(max_length=30)),
                ('dob', models.DateField(max_length=8)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(default='password', max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('adress', models.CharField(max_length=30)),
                ('zipcode', models.CharField(max_length=8)),
                ('country', models.CharField(max_length=20)),
                ('currency', models.CharField(max_length=2)),
                ('iban', models.CharField(max_length=34)),
            ],
        ),
        migrations.CreateModel(
            name='StockScreener',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('date_time', models.DateTimeField(unique=True)),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_backend.stock')),
            ],
        ),
        migrations.CreateModel(
            name='StockLogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('avg', models.FloatField()),
                ('max', models.FloatField()),
                ('mix', models.FloatField()),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_backend.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('token', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('expiry_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_backend.user')),
            ],
        ),
    ]
